### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by YUE-FAN** [Megvii-BaseDetection/DisAlign#10]
Hi, thanks for the great work. Maybe I missed it, but it seems that the code for this project has been incorporated into cvpods. I couldn't launch any experiments due to ImportErrors like:
`    from cvpods.layers import DisAlignLinear
ImportError: cannot import name 'DisAlignLinear' from 'cvpods.layers' `
Also, I didn't find the corresponding functions in cvpods.

Any help will be appreciated. Thanks.

**Comment by tonysy** [comment]
Sorry for the inconvenience. Please pull the latest commit of cvpods and re-install it. 
Feel free to ask questions if I can help.

**Comment by YUE-FAN** [comment]
Thanks for the quick reply. Now it works 👍
