### ISSUE TITLE
The code for semantic segmentation is missing

### ISSUE THREAD

**Issue by curiosity654** [Megvii-BaseDetection/DisAlign#11]
Hi, thank you for the nice work, but the code for semantic segmentation is missing and the URL for it in the README could not be opened. Could you please fix this issue?

**Comment by tonysy** [comment]
Thanks for your attention.
I will try my best to update the segmentation-related code this week.

**Comment by manmanjun** [comment]
> Thanks for your attention.
> I will try my best to update the segmentation-related code this week.

Hi, this is good work. When do you release the code for semantic segmentation?

**Comment by tonysy** [comment]
The semantic segmentation part has been updated. More pre-trained models will be updated this week.
