### ISSUE TITLE
The DisAlign_Seg page can't open

### ISSUE THREAD

**Issue by Kittywyk** [Megvii-BaseDetection/DisAlign#19]
Hi, thank you for your amazing work. 
I want to have a try on semantic segmentation problem. But the link [https://github.com/Megvii-BaseDetection/DisAlign/blob/main/TODO](url) of DisAlign_Seg cannot open. Could you pls have a look?
Thank you.

**Comment by tonysy** [comment]
Thanks for your attention. The semantic segmentation part has been released. More pre-trained models will be updated this week.
