### ISSUE TITLE
Where is the DisAlignLinear module?

### ISSUE THREAD

**Issue by jeongHwarr** [Megvii-BaseDetection/DisAlign#21]
Hello. Thank you for your impressive project!

I want to apply DisAlign to classification. 
However, an error occurs in the import part.
https://github.com/Megvii-BaseDetection/DisAlign/blob/a2fc3500a108cb83e3942293a5675c97ab3a2c6e/classification/imagenetlt/resnext50/resx50.scratch.imagenet_lt.224size.90e.disalign.10e/net.py#L7
I coudn't find the `DisAlignLinear` in `cvpods.layers`. 
and there also isn't exist at
[https://github.com/Megvii-BaseDetection/cvpods/tree/master/cvpods/layers](https://github.com/Megvii-BaseDetection/cvpods/tree/master/cvpods/layers)
How can I solve this problem?

Thank you!

**Comment by FateScript** [comment]
It's [here](https://github.com/Megvii-BaseDetection/cvpods/blob/ed05660eda3f8379a8df0a16ab464e112b4ce2fa/cvpods/layers/wrappers.py#L434)
Sorry, it's a bug in cvpods, I will fix this later.
You could use `from cvpods.layers.wrappers import DisAlignLinear` to work around this.

**Comment by jeongHwarr** [comment]
@FateScript Thank you so much!

**Comment by FateScript** [comment]
fixed now @jeongHwarr , please pull our latest branch.

**Comment by jeongHwarr** [comment]
@FateScript  Thank you!
