### ISSUE TITLE
scale in cosine classifier 

### ISSUE THREAD

**Issue by L1aoXingyu** [Megvii-BaseDetection/DisAlign#3]
Hi, thanks for your great work!
I notice you use the cosine classifier in many experiments and it can get a better baseline. The formula is as follows

![image](https://user-images.githubusercontent.com/19245504/115716657-fa5bfe00-a3ab-11eb-8808-8918b1b6f42d.png)

I am wondering the value of `s`?

**Comment by tonysy** [comment]
Hi, 
the initial value of `s` is set 20 typically and is learnable during the training process.

**Comment by L1aoXingyu** [comment]
Thanks for your reply!

**Comment by seekingup** [comment]
> Hi,
> the initial value of `s` is set 20 typically and is learnable during the training process.

Hi, I have a question. The scale `s` seems to be fixed in other method like De-Confound-TDE. Does the code of `DisAlign` use a different way and make it learnable?

**Comment by liming-ai** [comment]
> > Hi,
> > the initial value of `s` is set 20 typically and is learnable during the training process.
> 
> Hi, I have a question. The scale `s` seems to be fixed in other method like De-Confound-TDE. Does the code of `DisAlign` use a different way and make it learnable?

@tonysy @seekingup 

Same question, in other methods, the scale factor `s` is set to 30, like LDAM, De-Confound-TDE, and etc, I am wondering why you change it?

**Comment by tonysy** [comment]
Hi, fixed scale and learnable scale share similar performance on ImageNet-LT, but different datasets may require different scales, which is related to the number of classes and imbalance status.
