### ISSUE TITLE
ABOUT file "num_shots_v0.5.npy".

### ISSUE THREAD

**Issue by Liu-wanbing** [Megvii-BaseDetection/DisAlign#5]
Dear Author:
        Hi, is the file "num_shots_v0.5.npy" necessary for training? Can you provide the file?https://github.com/MegviiBaseDetection/DisAlign/blob/eb85ca08d2204c612e5ef1c54534d49a688dc838/segmentation/lvis0.5/mask_rcnn/res50/mask_rcnn.res50.fpn.lvis.multiscale.cos_norm.disalign.1x/roi_heads/fast_rcnn.py#L45

    def _init_weights(self, exp_scale=0.7):
        import os
        import cvpods
        import numpy as np
        folder_name = "/".join(cvpods.__path__[0].split('/')[:-1])
        num_samples_list = np.load(os.path.join(folder_name, "datasets/lvis/num_shots_v0.5.npy"))

**Comment by tonysy** [comment]
I have updated the readme and uploaded the related files. Feel free to re-open if you have any questions.
