### ISSUE TITLE
When will the classification code be released?

### ISSUE THREAD

**Issue by PyJulie** [Megvii-BaseDetection/DisAlign#7]

**Comment by tonysy** [comment]
Hi, we will release the code for classification and segmentation after the NeurIPS DDL, thanks for your attention

**Comment by YifanZhang07** [comment]
Ask again~

**Comment by tonysy** [comment]
Hi, part of the classification has been released, you need to re-install the cvpods.
More experiments of different models and datasets will be released soon.
