### ISSUE TITLE
About the reference Distribution p_r in Eq. (10)

### ISSUE THREAD

**Issue by Kevinz-code** [Megvii-BaseDetection/DisAlign#8]
Hi, 
Thank you for providing your code. 
Here I was wondering the Equation (10) in your paper (The definition of p_r), which seems not to be a distribution.
Since every x_i can only have one label, the reference distribution p_r(y| x_i)  will be the distribution like (0, 0, 0,...,w_c, 0, 0,...,0). And the sum of this distribution is w_c, but not 1.

Could you help me understand this equation? 
Thanks in advance.

**Comment by ghost** [comment]
Same question!
Hope there will be some further explanation.

**Comment by tonysy** [comment]
Please refer to #6 for this question.

**Comment by tonysy** [comment]
Feel free to re-open this issue if you have more questions.
