### ISSUE TITLE
about the confidence score σ(x)

### ISSUE THREAD

**Issue by lzed2399** [Megvii-BaseDetection/DisAlign#9]
In the paper, the σ(x) is implemented as a linear layer followed by a non-linear activation function (e.g., sigmoid function) for all input x. How to understand the input x？the matrix of raw iamge, or the extracted features, even or cls_score?
Thank you!

**Comment by tonysy** [comment]
Hi, the x of \sigma(x) is the extracted features.

**Comment by tonysy** [comment]
Feel free to reopen this issue if you have any questions.
